version: '3'
services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bff
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "db-data:/var/lib/mysql"
    restart: on-failure

  bff:
    build:
      dockerfile: Dockerfile
      context: .
    image: bff
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: bff
      MYSQL_PORT: 3306
      URL_ORQUESTRADOR: http://wiremock-server
      JAEGER_ENABLED: true
      APPLICATION_NAME: BFF
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_SAMPLER: 1
      SERVER_PORT: 8080
    restart: on-failure
    depends_on:
      - mysql

#  wiremock-server:
#    image: hellgate75/wiremock-server
#    container_name: wiremock-server
#    volumes:
#      - ./wiremock/mappings:/wiremock/mappings
#      - ./wiremock/wiremock-files:/wiremock/__files
#    ports:
#      - 9090:9090


  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/etc/prometheus/
    ports:
      - "9090:9090"
    mem_limit: 128m

  grafana:
    image: grafana/grafana:7.3.4
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

volumes:
  grafana-volume:
  prometheus-volume:
  db-data: